# Generated by Django 2.2.6 on 2019-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=100)),
                ('Mrdate', models.DateField()),
                ('Mlang', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movie_Info',
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=100)),
                ('Aage', models.IntegerField()),
                ('Agender', models.CharField(max_length=100)),
                ('Movi_Act', models.ManyToManyField(to='movie.Movie')),
            ],
            options={
                'db_table': 'actor_Info',
            },
        ),
    ]
